version: '2'
services:
  api:
    build: .
    container_name: 'metapos-api'
    image: debian/latest
    environment:
      - NODE_ENV=PRODUCTION
      - FOO=bar
      - DEBUG=*,-express*,-send,-mquery*,-follow*,-body*
      - LOG_LEVEL=info
      - MONGO_URI=mongodb://mongodb:27017/metapos
      - SECRET='super secret!'
      - PORT=3000
      - G_CLIENT_ID=945928903179-094k8q5lg0eknahtpt6fd1bg837hvdf6.apps.googleusercontent.com
    volumes:
      - .:/var/www:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    ports:
      - 3000:3000
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: 'mongo'
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
