version: '2'
services:
  api:
    build: .
    container_name: 'vertex'
    image: debian/latest
    environment:
      - NODE_ENV=PRODUCTION
      - LOG_LEVEL=silly
      - MONGO_URI=mongodb://mongodb:27017/vertex
      - SECRET='super secret!'
      - PORT=3000
    volumes:
      - .:/var/www:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    ports:
      - 3000:3000
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: 'v-mongo'
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
